language: perl
perl:
    - "5.16"
    - "5.14"
    - "5.12"
env:
    - MAXIMUS_CONFIG_LOCAL_SUFFIX=testing
before_install:
    - cpanm -n Module::Install
    - cpanm -n Catalyst::Devel
    - sudo apt-get install libdb-dev
    - yes | cpanm --verbose local::lib
notifications:
    irc:
        channels:
            - "irc.blitzed.org#maximus"
        use_notice: true
